# Generated by Django 5.1.7 on 2025-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_student_department_remove_student_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('content', models.TextField()),
            ],
        ),
    ]
